# NeON Build File (http://github.com/c4s4/neon)

default: go
extends: [golang, changelog]

properties:
  NAME:    'sawo-cards'
  LIBRARIES:
  - 'github.com/gin-gonic/gin'

targets:

  doc:
    doc: Build documentation
    steps:
    - mkdir: =BUILD_DIR
    - $: ['md2pdf', '-o', '={BUILD_DIR}/sawo-cards.pdf', 'README.md']

  run:
    doc: Build and run web service
    depends: [clean, bin]
    steps:
    - copy:  '*.png'
      dir:   'img'
      todir: =BUILD_DIR
    - chdir: =BUILD_DIR
    - $: ['./={NAME}', '../etc/configuration.yml']

  client:
    doc: Call web service
    steps:
    - mkdir: =BUILD_DIR
    - chdir: =BUILD_DIR
    - $:  ['curl', '-o', 'planche.png', 'http://sweetohm.net:8282/TEST/perso/pnj/joker/extras/background/intrigue/lieu/tresor']

  deploy:
    doc: Deploy binary on server
    depends: [clean, bin]
    steps:
    - print: 'Stopping service...'
    - $: ['ssh', 'root@elrond', 'systemctl stop sawo-cards']
    - print: 'Installing service...'
    - $: ['scp', '={BUILD_DIR}/={NAME}', 'sawo@elrond:~/']
    - print: 'Copying configuration...'
    - $: ['scp', 'etc/configuration.yml', 'sawo@elrond:~/']
    - print: 'Copying images...'
    - $: 'scp img/*.png sawo@elrond:~/'
    - print: 'Starting service...'
    - $: ['ssh', 'root@elrond', 'systemctl start sawo-cards']

  archive:
    doc: Generate installation archive
    depends: [clean, doc]
    steps:
    - copy:  '*.png'
      dir:   'img'
      todir: =BUILD_DIR
    - copy:  'planches.sh'
      dir:   'etc'
      todir: =BUILD_DIR
    - zip:    ['*.png', '*.sh', '*.pdf']
      dir:    =BUILD_DIR
      prefix: =NAME
      tofile: '={BUILD_DIR}/={NAME}.zip'

  token:
    doc: Generate a token
    steps:
    - $: ['go', 'run', 'etc/token.go']
